### ISSUE TITLE
依赖安装完后，出现了这个问题，大佬帮忙看下，我把该填的网址，apiKEY

### ISSUE THREAD

**Issue by lb1223** [qfds/Azure-OpenAI-LangChain-Chroma-KB#4]
configparser.NoSectionError: No section: 'Azure OpenAI'

**Comment by lb1223** [comment]
Traceback (most recent call last):
  File "c:\Users\46259\Documents\azure doc\Azure-OpenAI-LangChain-Chroma-KB-1\ai_system.py", line 38, in <module>
    openai.api_base = config.get('Azure OpenAI','https://chat-xaedu.openai.azure.com/')
  File "C:\Users\46259\anaconda3\lib\configparser.py", line 782, in get
    d = self._unify_values(section, vars)
  File "C:\Users\46259\anaconda3\lib\configparser.py", line 1153, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Azure OpenAI'

**Comment by lb1223** [comment]
我把该填的Endpoint和KEY 还有Deployment name都填了，这是哪里出问题了？

**Comment by qfds** [comment]
按照config.ini 填写，分成了两段，保证[Azure OpenAI]存在在你的配置文件中

**Comment by lb1223** [comment]
大佬，config.ini文件也按照要求填写了，而且为了方便我专门把所有Deployments的名字都改为model name了 ，检查了几遍了 还是不行
Exception has occurred: NoOptionError
No option 'https://chat-xaedu.openai.azure.com/' in section: 'Azure OpenAI'
KeyError: 'https://chat-xaedu.openai.azure.com/'

During handling of the above exception, another exception occurred:

  File "C:\Users\46259\Documents\azure doc\Azure-OpenAI-LangChain-Chroma-KB-1\ai_system.py", line 38, in <module>
    openai.api_base = config.get('Azure OpenAI','https://chat-xaedu.openai.azure.com/')
configparser.NoOptionError: No option 'https://chat-xaedu.openai.azure.com/' in section: 'Azure OpenAI'

**Comment by lb1223** [comment]
大师，我悟了，原来我是把ai.system里面的填写多了一个网页地址，已经能用了，感谢帮助(￣▽￣)"
